type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Truncate table CDS_ITEM_TEIR1_AVAILABILITY"
      parameters:
        componentName: "Start"
    Table Iterator:
      type: "table-iterator"
      transitions:
        success:
        - "Log Item Tier1 Availability Ingestion"
        failure:
        - "Log Item Tier1 Availability API Failure"
      iterationTarget: "CDS API Item Teir1 Availability"
      parameters:
        componentName: "Table Iterator"
        mode: "Advanced"
        query: "select bridge_key from PROD_BRONZE_DB.CDS.CDS_AUTH_KEYS"
        concurrency: "Concurrent"
        columnMapping1:
        - - "BRIDGE_KEY"
          - "v_auth_key"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    CDS API Item Teir1 Availability:
      type: "modular-api-extract-input-v2"
      parameters:
        componentName: "CDS API Item Teir1 Availability"
        componentId: "custom_v2-42592a6a-4709-47a9-84f4-1baa79265c2c"
        inputId: "api-extract-input-v2"
        api-extract-input-v2:
          profile: "custom-42592a6a-4709-47a9-84f4-1baa79265c2c"
          endpoint: "Item_Tier1_Availability"
          connectionRef:
            overrides:
              authType: "NONE"
          uriParams:
          queryParams:
          - name: "AuthKey"
            value: "${v_auth_key}"
          headerParams:
          postBody:
          pageLimit:
          logLevel: "ERROR"
          loadSelectedData: "No"
        outputId: "snowflake-output-connector-v0"
        snowflake-output-connector-v0:
          warehouse: "[Environment Default]"
          database: "[Environment Default]"
          schema: "[Environment Default]"
          tableName: "CDS_ITEM_TEIR1_AVAILABILITY"
          createTableMode: "APPEND"
          cleanStagedFiles: "Yes"
          stagePlatform: "SNOWFLAKE"
          snowflake#internalStageType: "USER"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Item Tier1 Availability API Failure:
      type: "sql-executor"
      parameters:
        componentName: "Log Item Tier1 Availability API Failure"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: |
          -- Log failure to audit table with error details
          INSERT INTO PROD_BRONZE_DB.CONFIG_SCH.CDS_AUDIT_LOG (
              TABLE_NAME,
              ROW_COUNT,
              LOAD_TIME,
              LOAD_STATUS,
              LOAD_TYPE,
              ERROR_MESSAGE
          )
          VALUES (
              'CDS_ITEM_TEIR1_AVAILABILITY',
              -1,  -- Negative count indicates failure
              CURRENT_TIMESTAMP,
              'FAILED',  -- Load status indicating failure
              'FULL LOAD',
              'Failed: Unknown error occurred during CDS CDS_ITEM_TEIR1_AVAILABILITY API processing'
          );
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Item Tier1 Availability Ingestion:
      type: "sql-executor"
      transitions:
        success:
        - "Data Parser Item Tier1 Availability"
      parameters:
        componentName: "Log Item Tier1 Availability Ingestion"
        scriptLocation: "Component"
        declareSqlVariables: "Include all"
        sqlScript: "-- Log success to audit table\nINSERT INTO PROD_BRONZE_DB.CONFIG_SCH.CDS_AUDIT_LOG\
          \ (\n    TABLE_NAME,\n    ROW_COUNT,\n    LOAD_TIME,\n    LOAD_STATUS,\n\
          \    LOAD_TYPE,\n    ERROR_MESSAGE\n)\nSELECT \n    'CDS_ITEM_TEIR1_AVAILABILITY'\
          \ AS TABLE_NAME,\n    COUNT(*) AS ROW_COUNT,\n    CURRENT_TIMESTAMP AS LOAD_TIME,\n\
          \    'SUCCESS' AS LOAD_STATUS,\n    'FULL LOAD' AS LOAD_TYPE,\n    NULL\
          \ AS ERROR_MESSAGE\nFROM PROD_BRONZE_DB.CDS.CDS_ITEM_TEIR1_AVAILABILITY;\n"
    Data Parser Item Tier1 Availability:
      type: "sql-executor"
      skipped: true
      parameters:
        componentName: "Data Parser Item Tier1 Availability"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "MERGE INTO prod_silver_db.CDS.CDS_ITEM_PRICING AS target\r\nUSING\
          \ (\r\n    SELECT \r\n        f.value:ItemCode::STRING AS ItemCode,\r\n\
          \        f.value:ItemPriceStatus::BOOLEAN AS ItemPriceStatus,\r\n      \
          \  f.value:Key::NUMBER AS Key,\r\n        f.value:OnsiteVisible::BOOLEAN\
          \ AS OnsiteVisible,\r\n        f.value:Price::NUMBER AS Price,\r\n     \
          \   f.value:Tier1::STRING AS Tier1,\r\n        f.value:Tier2::STRING AS\
          \ Tier2,\r\n        f.value:Tier3::STRING AS Tier3,\r\n        f.value:Tier4::STRING\
          \ AS Tier4,\r\n        f.value:Tier5::STRING AS Tier5\r\n    FROM prod_bronze_db.CDS.CDS_ITEM_PRICING\
          \ p,\r\n    LATERAL FLATTEN(input => p.\"ItemPriceDefinitionRecords\") f\r\
          \n) AS source\r\nON target.Key = source.Key\r\n\r\nWHEN MATCHED THEN\r\n\
          \    UPDATE SET \r\n        target.ItemCode = source.ItemCode,\r\n     \
          \   target.ItemPriceStatus = source.ItemPriceStatus,\r\n        target.OnsiteVisible\
          \ = source.OnsiteVisible,\r\n        target.Price = source.Price,\r\n  \
          \      target.Tier1 = source.Tier1,\r\n        target.Tier2 = source.Tier2,\r\
          \n        target.Tier3 = source.Tier3,\r\n        target.Tier4 = source.Tier4,\r\
          \n        target.Tier5 = source.Tier5\r\n\r\nWHEN NOT MATCHED THEN\r\n \
          \   INSERT (\r\n        ItemCode, ItemPriceStatus, Key, OnsiteVisible, Price,\r\
          \n        Tier1, Tier2, Tier3, Tier4, Tier5\r\n    )\r\n    VALUES (\r\n\
          \        source.ItemCode, source.ItemPriceStatus, source.Key, source.OnsiteVisible,\
          \ source.Price,\r\n        source.Tier1, source.Tier2, source.Tier3, source.Tier4,\
          \ source.Tier5\r\n    );\r\n"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Truncate table CDS_ITEM_TEIR1_AVAILABILITY:
      type: "sql-executor"
      transitions:
        success:
        - "Table Iterator"
      skipped: true
      parameters:
        componentName: "Truncate table CDS_ITEM_TEIR1_AVAILABILITY"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "TRUNCATE TABLE PROD_BRONZE_DB.CDS.CDS_ITEM_TEIR1_AVAILABILITY;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_auth_key:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "BE4666DC-A56A-4B6D-B01E-5ED4BC888856"
design:
  components:
    Start:
      position:
        x: -110
        "y": 0
      tempMetlId: 1
    Table Iterator:
      position:
        x: 170
        "y": -20
      tempMetlId: 2
    CDS API Item Teir1 Availability:
      position:
        x: 170
        "y": -20
      tempMetlId: 3
    Log Item Tier1 Availability API Failure:
      position:
        x: 330
        "y": -100
      tempMetlId: 4
    Log Item Tier1 Availability Ingestion:
      position:
        x: 330
        "y": 0
      tempMetlId: 5
    Data Parser Item Tier1 Availability:
      position:
        x: 480
        "y": 0
      tempMetlId: 6
    Truncate table CDS_ITEM_TEIR1_AVAILABILITY:
      position:
        x: 10
        "y": 0
      tempMetlId: 7
