type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Table Iterator"
      parameters:
        componentName: "Start"
    CDS API Item Pricing:
      type: "modular-api-extract-input-v2"
      parameters:
        componentName: "CDS API Item Pricing"
        componentId: "custom_v2-42592a6a-4709-47a9-84f4-1baa79265c2c"
        inputId: "api-extract-input-v2"
        api-extract-input-v2:
          profile: "custom-42592a6a-4709-47a9-84f4-1baa79265c2c"
          endpoint: "Item_Pricing"
          connectionRef:
            overrides:
              authType: "NONE"
          uriParams:
          queryParams:
          - name: "AuthKey"
            value: "${v_auth_key}"
          headerParams:
          postBody:
          pageLimit:
          logLevel: "ERROR"
          loadSelectedData: "No"
        outputId: "snowflake-output-connector-v0"
        snowflake-output-connector-v0:
          warehouse: "[Environment Default]"
          database: "[Environment Default]"
          schema: "[Environment Default]"
          tableName: "CDS_ITEM_PRICING"
          createTableMode: "APPEND"
          cleanStagedFiles: "Yes"
          stagePlatform: "SNOWFLAKE"
          snowflake#internalStageType: "USER"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Table Iterator:
      type: "table-iterator"
      iterationTarget: "CDS API Item Pricing"
      parameters:
        componentName: "Table Iterator"
        mode: "Advanced"
        query: "select bridge_key from PROD_BRONZE_DB.CDS.CDS_AUTH_KEYS"
        concurrency: "Concurrent"
        columnMapping1:
        - - "BRIDGE_KEY"
          - "v_auth_key"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_auth_key:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "BE4666DC-A56A-4B6D-B01E-5ED4BC888856"
design:
  components:
    Start:
      position:
        x: -90
        "y": -30
      tempMetlId: 1
    CDS API Item Pricing:
      position:
        x: 50
        "y": -50
      tempMetlId: 2
    Table Iterator:
      position:
        x: 50
        "y": -50
      tempMetlId: 3
