type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Truncate table CDS_REGISTRATION_CATEGORY"
      parameters:
        componentName: "Start"
    Table Iterator:
      type: "table-iterator"
      transitions:
        success:
        - "Log Registration Category Ingestion"
        failure:
        - "Log Registration Category API Failure"
      iterationTarget: "CDS API Registration Category"
      parameters:
        componentName: "Table Iterator"
        mode: "Advanced"
        query: "select bridge_key from PROD_BRONZE_DB.CDS.CDS_AUTH_KEYS"
        concurrency: "Concurrent"
        columnMapping1:
        - - "BRIDGE_KEY"
          - "v_auth_key"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    CDS API Registration Category:
      type: "modular-api-extract-input-v2"
      parameters:
        componentName: "CDS API Registration Category"
        componentId: "custom_v2-42592a6a-4709-47a9-84f4-1baa79265c2c"
        inputId: "api-extract-input-v2"
        api-extract-input-v2:
          profile: "custom-42592a6a-4709-47a9-84f4-1baa79265c2c"
          endpoint: "Registration_Category_Read"
          connectionRef:
            overrides:
              authType: "NONE"
          uriParams:
          queryParams:
          - name: "AuthKey"
            value: "${v_auth_key}"
          headerParams:
          postBody:
          pageLimit:
          logLevel: "ERROR"
          loadSelectedData: "No"
        outputId: "snowflake-output-connector-v0"
        snowflake-output-connector-v0:
          warehouse: "[Environment Default]"
          database: "[Environment Default]"
          schema: "[Environment Default]"
          tableName: "CDS_REGISTRATION_CATEGORY"
          createTableMode: "APPEND"
          cleanStagedFiles: "Yes"
          stagePlatform: "SNOWFLAKE"
          snowflake#internalStageType: "USER"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log Registration Category Ingestion:
      type: "sql-executor"
      transitions:
        success:
        - "Data Parser Registration Category"
      parameters:
        componentName: "Log Registration Category Ingestion"
        scriptLocation: "Component"
        declareSqlVariables: "Include all"
        sqlScript: "-- Log success to audit table\nINSERT INTO PROD_BRONZE_DB.CONFIG_SCH.CDS_AUDIT_LOG\
          \ (\n    TABLE_NAME,\n    ROW_COUNT,\n    LOAD_TIME,\n    LOAD_STATUS,\n\
          \    LOAD_TYPE,\n    ERROR_MESSAGE\n)\nSELECT \n    'CDS_REGISTRATION_CATEGORY'\
          \ AS TABLE_NAME,\n    COUNT(*) AS ROW_COUNT,\n    CURRENT_TIMESTAMP AS LOAD_TIME,\n\
          \    'SUCCESS' AS LOAD_STATUS,\n    'FULL LOAD' AS LOAD_TYPE,\n    NULL\
          \ AS ERROR_MESSAGE\nFROM PROD_BRONZE_DB.CDS.CDS_REGISTRATION_CATEGORY;\n"
    Log Registration Category API Failure:
      type: "sql-executor"
      parameters:
        componentName: "Log Registration Category API Failure"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: |
          -- Log failure to audit table with error details
          INSERT INTO PROD_BRONZE_DB.CONFIG_SCH.CDS_AUDIT_LOG (
              TABLE_NAME,
              ROW_COUNT,
              LOAD_TIME,
              LOAD_STATUS,
              LOAD_TYPE,
              ERROR_MESSAGE
          )
          VALUES (
              'CDS_REGISTRATION_CATEGORY',
              -1,  -- Negative count indicates failure
              CURRENT_TIMESTAMP,
              'FAILED',  -- Load status indicating failure
              'FULL LOAD',
              'Failed: Unknown error occurred during CDS CDS_REGISTRATION_CATEGORY API processing'
          );
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Data Parser Registration Category:
      type: "sql-executor"
      skipped: false
      parameters:
        componentName: "Data Parser Registration Category"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "MERGE INTO PROD_SILVER_DB.CDS.CDS_REGISTRATION_CATEGORY AS target\r\
          \nUSING (\r\n    SELECT \r\n        f.value:RegistrationCategoryCode::STRING\
          \ AS RegistrationCategoryCode,\r\n        f.value:CategoryDescription::STRING\
          \ AS CategoryDescription,\r\n        f.value:Grouping::STRING AS Grouping,\r\
          \n        f.value:IsAttending::BOOLEAN AS IsAttending\r\n    FROM PROD_BRONZE_DB.CDS.CDS_REGISTRATION_CATEGORY\
          \ r,\r\n    LATERAL FLATTEN(input => r.\"RegistrationCategoryRecords\")\
          \ f\r\n) AS source\r\nON target.RegistrationCategoryCode = source.RegistrationCategoryCode\r\
          \n\r\n-- WHEN MATCHED THEN\r\n--     UPDATE SET \r\n--         target.CategoryDescription\
          \ = source.CategoryDescription,\r\n--         target.Grouping = source.Grouping,\r\
          \n--         target.IsAttending = source.IsAttending\r\n\r\nWHEN NOT MATCHED\
          \ THEN\r\n    INSERT (\r\n        RegistrationCategoryCode, CategoryDescription,\
          \ Grouping, IsAttending\r\n    )\r\n    VALUES (\r\n        source.RegistrationCategoryCode,\
          \ source.CategoryDescription, source.Grouping, source.IsAttending\r\n  \
          \  );"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Truncate table CDS_REGISTRATION_CATEGORY:
      type: "sql-executor"
      transitions:
        success:
        - "Table Iterator"
      parameters:
        componentName: "Truncate table CDS_REGISTRATION_CATEGORY"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "TRUNCATE TABLE PROD_BRONZE_DB.CDS.CDS_REGISTRATION_CATEGORY;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_auth_key:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "BE4666DC-A56A-4B6D-B01E-5ED4BC888856"
design:
  components:
    Start:
      position:
        x: -110
        "y": 0
      tempMetlId: 1
    Table Iterator:
      position:
        x: 160
        "y": -20
      tempMetlId: 2
    CDS API Registration Category:
      position:
        x: 160
        "y": -20
      tempMetlId: 3
    Log Registration Category Ingestion:
      position:
        x: 330
        "y": 0
      tempMetlId: 4
    Log Registration Category API Failure:
      position:
        x: 330
        "y": -90
      tempMetlId: 5
    Data Parser Registration Category:
      position:
        x: 500
        "y": 0
      tempMetlId: 6
    Truncate table CDS_REGISTRATION_CATEGORY:
      position:
        x: 20
        "y": 0
      tempMetlId: 7
