type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Trncate Event Session details table "
      parameters:
        componentName: "Start"
    Run Event Session Transform:
      type: "run-orchestration"
      parameters:
        componentName: "Run Event Session Transform"
        orchestrationJob: "lms_data_ingestion/LMS Incremental Data Ingestion/pl_lms_event_session_details_transformation_incremental.orch.yaml"
        setScalarVariables:
        - - "v_event_id"
          - "${v_event_id}"
    Table Iterator:
      type: "table-iterator"
      transitions:
        success:
        - "Log event session detail ingestion"
        failure:
        - "Log LMS API Failure"
      iterationTarget: "Run Event Session Transform"
      parameters:
        componentName: "Table Iterator"
        mode: "Advanced"
        query: "SELECT\r\n    item.value:id::STRING AS id\r\nFROM PROD_BRONZE_DB.LMS.EVENTS,\r\
          \n     LATERAL FLATTEN(input => DATA_VALUE:data) AS item"
        concurrency: "Sequential"
        columnMapping1:
        - - "ID"
          - "v_event_id"
        breakOnFailure: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log event session detail ingestion:
      type: "sql-executor"
      transitions:
        success:
        - "Data Parser Event Session "
      parameters:
        componentName: "Log event session detail ingestion"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "-- Log success to audit table\nINSERT INTO PROD_BRONZE_DB.LMS.LMS_AUDIT_LOG\
          \ (\n    TABLE_NAME,\n    ROW_COUNT,\n    LOAD_TIME,\n    LOAD_STATUS,\n\
          \    ERROR_MESSAGE\n)\nSELECT \n    'EVENT_SESSION_DETAILS' AS TABLE_NAME,\n\
          \    COUNT(*) AS ROW_COUNT,\n    CURRENT_TIMESTAMP AS LOAD_TIME,\n    'SUCCESS'\
          \ AS LOAD_STATUS,\n    NULL AS ERROR_MESSAGE\nFROM PROD_BRONZE_DB.LMS.EVENT_SESSION_DETAILS;\n"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    'Data Parser Event Session ':
      type: "sql-executor"
      transitions:
        success:
        - "drop event session details raw table "
      parameters:
        componentName: "Data Parser Event Session "
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: |-
          MERGE INTO PROD_SILVER_DB.LMS.EVENT_SESSION_DETAILS AS target
          USING PROD_BRONZE_DB.LMS.EVENT_SESSION_DETAILS AS source
          ON target.SESSION_ID = source.SESSION_ID
          AND target.EVENT_ID = source.EVENT_ID

          WHEN MATCHED THEN
              UPDATE SET
                  target.EVENT_ID = source.EVENT_ID,
                  target.EVAL_ID = source.EVAL_ID,
                  target.START_TIME = source.START_TIME,
                  target.END_TIME = source.END_TIME,
                  target.TIMEZONE = source.TIMEZONE,
                  target.PRODUCT_ID = source.PRODUCT_ID,
                  target.PRODUCT_IDENTIFICATION = source.PRODUCT_IDENTIFICATION,
                  target.PRODUCT_NAME = source.PRODUCT_NAME,
                  target.PRODUCT_TYPE = source.PRODUCT_TYPE,
                  target.SESSION_TITLE = source.SESSION_TITLE

          WHEN NOT MATCHED THEN
              INSERT (
                  EVENT_ID,
                  SESSION_ID,
                  EVAL_ID,
                  START_TIME,
                  END_TIME,
                  TIMEZONE,
                  PRODUCT_ID,
                  PRODUCT_IDENTIFICATION,
                  PRODUCT_NAME,
                  PRODUCT_TYPE,
                  SESSION_TITLE
              )
              VALUES (
                  source.EVENT_ID,
                  source.SESSION_ID,
                  source.EVAL_ID,
                  source.START_TIME,
                  source.END_TIME,
                  source.TIMEZONE,
                  source.PRODUCT_ID,
                  source.PRODUCT_IDENTIFICATION,
                  source.PRODUCT_NAME,
                  source.PRODUCT_TYPE,
                  source.SESSION_TITLE
              );
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Log LMS API Failure:
      type: "sql-executor"
      parameters:
        componentName: "Log LMS API Failure"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: |
          -- Log failure to audit table with error details
          INSERT INTO PROD_BRONZE_DB.LMS.LMS_AUDIT_LOG (
              TABLE_NAME,
              ROW_COUNT,
              LOAD_TIME,
              LOAD_STATUS,
              ERROR_MESSAGE
          )
          VALUES (
              'EVENT_SESSION_DETAILS',
              -1,  -- Negative count indicates failure
              CURRENT_TIMESTAMP,
              'FAILED',  -- Load status indicating failure
              'Failed Unknown error occurred during LMS API batch processing'
          );
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    'Trncate Event Session details table ':
      type: "sql-executor"
      transitions:
        success:
        - "Table Iterator"
      parameters:
        componentName: "Trncate Event Session details table "
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "TRUNCATE TABLE PROD_BRONZE_DB.LMS.EVENT_SESSION_DETAILS;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    'drop event session details raw table ':
      type: "sql-executor"
      parameters:
        componentName: "drop event session details raw table "
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "drop table PROD_BRONZE_DB.LMS.EVENT_SESSION_DETAILS_RAW;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    v_event_id:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "39d0efc1-5d3c-40f8-ad2b-85d7310998aa"
design:
  components:
    Start:
      position:
        x: -380
        "y": 20
      tempMetlId: 1
    Run Event Session Transform:
      position:
        x: -120
        "y": 0
      tempMetlId: 3
    Table Iterator:
      position:
        x: -120
        "y": 0
      tempMetlId: 4
    Log event session detail ingestion:
      position:
        x: 10
        "y": 20
      tempMetlId: 6
    'Data Parser Event Session ':
      position:
        x: 140
        "y": 20
      tempMetlId: 7
    Log LMS API Failure:
      position:
        x: 80
        "y": -80
      tempMetlId: 9
    'Trncate Event Session details table ':
      position:
        x: -260
        "y": 20
      tempMetlId: 10
    'drop event session details raw table ':
      position:
        x: 270
        "y": 20
      tempMetlId: 11
